---
- name: Install flask on Linux system
  hosts: ubuntu
  become: true
  become_user: root
  gather_facts: true
  tasks:
  - name: Installing Flask
    pip:
      name: flask
      state: present
