---
- name: Install and configure Jenkins
  hosts: jenkins
  become_user: root
  become: true
  gather_facts: true
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
    - role: geerlingguy.jenkins


    